{{- if .Values.services.escolar.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caqi.fullname" . }}-escolar
  labels:
    {{- include "caqi.labels" . | nindent 4 }}
    app.kubernetes.io/component: escolar
spec:
  replicas: {{ .Values.services.escolar.replicas }}
  selector:
    matchLabels:
      {{- include "caqi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: escolar
  template:
    metadata:
      labels:
        {{- include "caqi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: escolar
    spec:
      serviceAccountName: {{ include "caqi.fullname" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: escolar
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/caq-escolar-svc:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.services.escolar.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "caqi.fullname" . }}-env
          env:
            - name: SERVER_PORT
              value: "{{ .Values.services.escolar.port }}"
            - name: OTEL_SERVICE_NAME
              value: caq-escolar-svc
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.external.existingSecret }}
                  key: {{ .Values.postgresql.external.existingSecretKey }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.external.existingSecret }}
                  key: {{ .Values.rabbitmq.external.existingSecretKey }}
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            initialDelaySeconds: 15
            periodSeconds: 5
          resources: {{- toYaml .Values.services.escolar.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caqi.fullname" . }}-escolar
  labels:
    {{- include "caqi.labels" . | nindent 4 }}
    app.kubernetes.io/component: escolar
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.escolar.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "caqi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: escolar
{{- end }}
